### ISSUE TITLE
Cant find the material list!

### ISSUE THREAD

**Issue by Pocke01** [Leoneq/iNapMalinka#6]
Like the title says. I can only find some parts under features but I would like to have all the parts. Could you please add a material list. :)

**Comment by Leoneq** [comment]
Hi! The part list is included as a BOM file in the 'pcb' folder: [BOM_iNapMalinka32.csv](https://github.com/Leoneq/iNapMalinka/blob/main/pcb/BOM_iNapMalinka32.csv)

**Comment by Pocke01** [comment]
Thank you!  How could i miss that one.
